version: "3.7"
services:
  nginx:
    image: nginx:latest
    networks:
      - network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - static:/home/SEEYA-ARCHIVE-BACK/staticfiles
      - media:/home/SEEYA-ARCHIVE-BACK/media
    ports:
      - 80:80
    depends_on:
      - postgredb
      - gunicorn_server
    restart: always


  gunicorn_server:
    image: django_server:1
    networks:
      - network
    volumes:
      - static:/home/SEEYA-ARCHIVE-BACK/staticfiles
      - media:/home/SEEYA-ARCHIVE-BACK/media
    depends_on:
      - postgredb
    restart: always
    secrets:
      - SECRET_KEY
      - MY_AWS_SECRET_ACCESS_KEY
      - MY_AWS_ACCESS_KEY_ID
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - HOST

  postgredb:
      image: postgres:latest
      networks:
        - network
      ports:
        - 5432:5432
      environment:
        POSTGRES_DB: seeyadb
        POSTGRES_PASSWORD: seeyaarchive123!
        POSTGRES_USER: seeyadb
      restart: always

networks:
  network:

volumes:
  static:
  media:

secrets:
  SECRET_KEY:
    external: true
  MY_AWS_SECRET_ACCESS_KEY:
    external: true
  MY_AWS_ACCESS_KEY_ID:
    external: true
  DB_NAME:
    external: true
  DB_USER:
    external: true
  DB_PASSWORD:
    external: true
  DB_HOST:
    external: true
  DB_PORT:
    external: true
  HOST:
    external: true