# Generated by Django 4.0.3 on 2022-04-09 02:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=1024)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('concert_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='concert_halls.concerthall')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=128)),
                ('seat_row', models.CharField(blank=True, max_length=128, null=True)),
                ('seat_num', models.CharField(blank=True, max_length=128, null=True)),
                ('seat_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='concert_halls.floor')),
            ],
        ),
    ]
