# Generated by Django 4.0.3 on 2022-04-10 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concert_halls', '0002_alter_seatarea_concert_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatarea',
            name='concert_hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_areas', to='concert_halls.concerthall'),
        ),
    ]
