# Generated by Django 4.0.3 on 2022-04-09 02:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import seat_reviews.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concert_halls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_hall', models.CharField(blank=True, default='올림픽홀', max_length=128, null=True)),
                ('source_url', models.URLField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to=seat_reviews.models.get_seat_image_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=seat_reviews.models.get_seat_image_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=seat_reviews.models.get_seat_image_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=seat_reviews.models.get_seat_image_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=seat_reviews.models.get_seat_image_path)),
                ('text', models.TextField(blank=True, null=True)),
                ('floor', models.CharField(blank=True, max_length=128, null=True)),
                ('area', models.CharField(blank=True, max_length=128, null=True)),
                ('seat_row', models.CharField(blank=True, max_length=128, null=True)),
                ('seat_num', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), size=None)),
                ('artist', models.CharField(blank=True, max_length=128, null=True)),
                ('floor', models.CharField(max_length=128)),
                ('area', models.CharField(max_length=128)),
                ('seat_row', models.CharField(blank=True, max_length=128, null=True)),
                ('seat_num', models.CharField(blank=True, max_length=128, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('concert_hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concert_halls.concerthall')),
            ],
        ),
    ]
