# Generated by Django 4.0.3 on 2022-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpost',
            name='concert_hall',
            field=models.CharField(blank=True, default='올림픽홀', max_length=128, null=True),
        ),
    ]
