# Generated by Django 4.0.3 on 2022-04-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concert_halls', '0002_alter_seatarea_concert_hall'),
        ('seat_reviews', '0002_alter_post_seat_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seat_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='concert_halls.seatarea'),
        ),
    ]
