# Generated by Django 4.0.3 on 2022-04-11 13:31

import django.contrib.postgres.fields
from django.db import migrations, models
import seat_reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('seat_reviews', '0005_review_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=seat_reviews.models.get_review_image_path), size=None),
        ),
    ]
