# Generated by Django 3.2.12 on 2022-04-16 02:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat_reviews', '0006_alter_review_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), size=None),
        ),
    ]
